[tools]
# YAML
uv = "latest" # for yamllint

# Markdown
"npm:markdownlint-cli" = "latest"

# JSON
biome = "latest"

# GitHub Actions
actionlint = "latest"
shellcheck = "latest"

# Terraform
terraform = "latest"

# Others
fzf = "latest"
